/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DocSummarizePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_CHAT = "doc-summarize-chat-view";
var DEFAULT_SETTINGS = {
  lmStudioUrl: "http://localhost:1234/v1",
  model: "",
  maxTokens: 2048,
  temperature: 0.7,
  summarizePrompt: `\u0422\u044B - \u043F\u043E\u043C\u043E\u0449\u043D\u0438\u043A \u0434\u043B\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432. \u0421\u043E\u0437\u0434\u0430\u0439 \u043A\u0440\u0430\u0442\u043A\u043E\u0435 \u0438 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0442\u0438\u0432\u043D\u043E\u0435 \u0440\u0435\u0437\u044E\u043C\u0435 \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u0433\u043E \u0442\u0435\u043A\u0441\u0442\u0430 \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435. \u0412\u044B\u0434\u0435\u043B\u0438 \u043A\u043B\u044E\u0447\u0435\u0432\u044B\u0435 \u043C\u043E\u043C\u0435\u043D\u0442\u044B \u0438 \u043E\u0441\u043D\u043E\u0432\u043D\u044B\u0435 \u0438\u0434\u0435\u0438.`,
  questionPrompt: `\u0422\u044B - \u043F\u043E\u043C\u043E\u0449\u043D\u0438\u043A \u0434\u043B\u044F \u043E\u0442\u0432\u0435\u0442\u043E\u0432 \u043D\u0430 \u0432\u043E\u043F\u0440\u043E\u0441\u044B \u043E \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u0445. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439 \u043F\u0440\u0435\u0434\u043E\u0441\u0442\u0430\u0432\u043B\u0435\u043D\u043D\u044B\u0439 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442 \u0434\u043B\u044F \u043E\u0442\u0432\u0435\u0442\u0430. \u0415\u0441\u043B\u0438 \u0432 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0435 \u0435\u0441\u0442\u044C \u0441\u0441\u044B\u043B\u043A\u0438 \u043D\u0430 \u0434\u0440\u0443\u0433\u0438\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438, \u0443\u043F\u043E\u043C\u0438\u043D\u0430\u0439 \u0438\u0445 \u0432 \u0444\u043E\u0440\u043C\u0430\u0442\u0435 [[\u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438]] \u0438\u043B\u0438 [[\u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430]]. \u041E\u0442\u0432\u0435\u0447\u0430\u0439 \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435.`,
  includeLinkedNotes: true,
  maxLinkedNotesDepth: 1,
  language: "ru",
  maxContextLength: 4e3,
  // Максимальная длина контекста в символах
  useMapReduce: false,
  // Использовать Map-Reduce для больших наборов документов
  maxFileAge: 0,
  // Максимальный возраст файлов в днях (0 - все)
  useFileIndex: true,
  // Использовать индекс файлов вместо полного контента
  maxIndexFiles: 50
  // Максимальное количество файлов в индексе
};
var DocSummarizePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.availableModels = [];
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatSidebarView(leaf, this));
    this.addRibbonIcon("message-square", "Doc Summarize Chat", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "open-chat-sidebar",
      name: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0447\u0430\u0442 \u0432 \u0431\u043E\u043A\u043E\u0432\u043E\u0439 \u043F\u0430\u043D\u0435\u043B\u0438",
      callback: () => {
        this.activateChatView();
      }
    });
    this.addCommand({
      id: "summarize-current-document",
      name: "\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0442\u0435\u043A\u0443\u0449\u0438\u0439 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442",
      editorCallback: (editor, view) => {
        const content = editor.getValue();
        const file = view.file;
        this.summarizeContent(content, (file == null ? void 0 : file.basename) || "\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442");
      }
    });
    this.addCommand({
      id: "summarize-selection",
      name: "\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0432\u044B\u0434\u0435\u043B\u0435\u043D\u043D\u044B\u0439 \u0442\u0435\u043A\u0441\u0442",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (selection) {
          this.summarizeContent(selection, "\u0412\u044B\u0434\u0435\u043B\u0435\u043D\u043D\u044B\u0439 \u0442\u0435\u043A\u0441\u0442");
        } else {
          new import_obsidian.Notice("\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0432\u044B\u0434\u0435\u043B\u0438\u0442\u0435 \u0442\u0435\u043A\u0441\u0442 \u0434\u043B\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438");
        }
      }
    });
    this.addCommand({
      id: "ask-about-document",
      name: "\u0417\u0430\u0434\u0430\u0442\u044C \u0432\u043E\u043F\u0440\u043E\u0441 \u043E \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0435",
      editorCallback: (editor, view) => {
        const content = editor.getValue();
        const file = view.file;
        new ChatModal(this.app, this, content, file).open();
      }
    });
    this.addCommand({
      id: "summarize-image",
      name: "\u041E\u043F\u0438\u0441\u0430\u0442\u044C/\u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
      callback: () => {
        new ImageSummarizeModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "ask-about-vault",
      name: "\u0417\u0430\u0434\u0430\u0442\u044C \u0432\u043E\u043F\u0440\u043E\u0441 \u043E \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u0445 (\u043F\u043E\u0438\u0441\u043A \u043F\u043E vault)",
      callback: () => {
        new VaultChatModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "insert-summary",
      name: "\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044C \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044E \u0432 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442",
      editorCallback: async (editor, view) => {
        const content = editor.getValue();
        const summary = await this.getSummary(content);
        if (summary) {
          const cursor = editor.getCursor();
          editor.replaceRange(
            `

---
## \u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F

${summary}

---
`,
            cursor
          );
          new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442");
        }
      }
    });
    this.addSettingTab(new DocSummarizeSettingTab(this.app, this));
    const statusBarItem = this.addStatusBarItem();
    statusBarItem.addClass("doc-summarize-status");
    this.updateStatusBar(statusBarItem);
    this.loadAvailableModels();
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHAT);
  }
  // Активация боковой панели чата
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // Получение списка доступных моделей
  async loadAvailableModels() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.settings.lmStudioUrl}/models`,
        method: "GET"
      });
      if (response.status === 200) {
        const data = response.json;
        this.availableModels = data.data || [];
        if (!this.settings.model && this.availableModels.length > 0) {
          this.settings.model = this.availableModels[0].id;
          await this.saveSettings();
        }
        return this.availableModels;
      }
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043A\u0438 \u043C\u043E\u0434\u0435\u043B\u0435\u0439:", error);
    }
    return [];
  }
  // Проверка подключения к LM Studio
  async checkConnection() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.settings.lmStudioUrl}/models`,
        method: "GET"
      });
      return response.status === 200;
    } catch (error) {
      console.error("LM Studio connection error:", error);
      return false;
    }
  }
  // Обновление статус-бара
  async updateStatusBar(statusBarItem) {
    const connected = await this.checkConnection();
    statusBarItem.empty();
    const dot = statusBarItem.createSpan({ cls: "doc-summarize-status-dot" });
    dot.addClass(connected ? "connected" : "disconnected");
    statusBarItem.createSpan({ text: connected ? "LM Studio" : "LM Studio (offline)" });
  }
  // Отправка запроса к LM Studio API
  async sendToLMStudio(messages, onStream) {
    var _a, _b, _c, _d, _e, _f;
    try {
      const requestBody = {
        model: this.settings.model,
        messages: messages.map((m) => {
          if (m.images && m.images.length > 0) {
            return {
              role: m.role,
              content: [
                { type: "text", text: m.content },
                ...m.images.map((img) => ({
                  type: "image_url",
                  image_url: { url: img }
                }))
              ]
            };
          }
          return { role: m.role, content: m.content };
        }),
        max_tokens: this.settings.maxTokens,
        temperature: this.settings.temperature,
        stream: !!onStream
      };
      if (onStream) {
        const response = await fetch(`${this.settings.lmStudioUrl}/chat/completions`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(requestBody)
        });
        if (!response.ok) {
          throw new Error(`API Error: ${response.status}`);
        }
        const reader = (_a = response.body) == null ? void 0 : _a.getReader();
        if (!reader) {
          throw new Error("No response body");
        }
        let fullContent = "";
        const decoder = new TextDecoder();
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const chunk = decoder.decode(value, { stream: true });
          const lines = chunk.split("\n");
          for (const line of lines) {
            if (line.startsWith("data: ")) {
              const data = line.slice(6);
              if (data === "[DONE]")
                continue;
              try {
                const parsed = JSON.parse(data);
                const content = ((_d = (_c = (_b = parsed.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta) == null ? void 0 : _d.content) || "";
                if (content) {
                  fullContent += content;
                  onStream(fullContent);
                }
              } catch (e) {
              }
            }
          }
        }
        return fullContent;
      } else {
        const response = await (0, import_obsidian.requestUrl)({
          url: `${this.settings.lmStudioUrl}/chat/completions`,
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(requestBody)
        });
        if (response.status !== 200) {
          throw new Error(`API Error: ${response.status}`);
        }
        const data = response.json;
        return ((_f = (_e = data.choices[0]) == null ? void 0 : _e.message) == null ? void 0 : _f.content) || "";
      }
    } catch (error) {
      console.error("LM Studio API error:", error);
      throw error;
    }
  }
  // Получение суммаризации
  async getSummary(content) {
    try {
      const messages = [
        { role: "system", content: this.settings.summarizePrompt },
        { role: "user", content }
      ];
      return await this.sendToLMStudio(messages);
    } catch (error) {
      new import_obsidian.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio.");
      return null;
    }
  }
  // Суммаризация контента с показом модального окна
  async summarizeContent(content, title) {
    new SummaryModal(this.app, this, content, title).open();
  }
  // Получение связанных заметок
  async getLinkedNotes(file, depth = 1) {
    const linkedNotes = /* @__PURE__ */ new Map();
    if (depth <= 0)
      return linkedNotes;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.links))
      return linkedNotes;
    for (const link of cache.links) {
      const linkedFile = this.app.metadataCache.getFirstLinkpathDest(
        link.link,
        file.path
      );
      if (linkedFile && linkedFile instanceof import_obsidian.TFile && !linkedNotes.has(linkedFile.path)) {
        const content = await this.app.vault.read(linkedFile);
        linkedNotes.set(linkedFile.path, `## ${linkedFile.basename}

${content}`);
        if (depth > 1) {
          const nestedLinks = await this.getLinkedNotes(linkedFile, depth - 1);
          nestedLinks.forEach((value, key) => {
            if (!linkedNotes.has(key)) {
              linkedNotes.set(key, value);
            }
          });
        }
      }
    }
    return linkedNotes;
  }
  // Поиск заметок по запросу
  async searchNotes(query) {
    const files = this.app.vault.getMarkdownFiles();
    const results = [];
    const queryLower = query.toLowerCase();
    const queryWords = queryLower.split(/\s+/);
    for (const file of files) {
      let score = 0;
      const content = await this.app.vault.cachedRead(file);
      const contentLower = content.toLowerCase();
      const titleLower = file.basename.toLowerCase();
      for (const word of queryWords) {
        if (titleLower.includes(word))
          score += 10;
        if (contentLower.includes(word))
          score += 1;
      }
      if (score > 0) {
        results.push({ file, score });
      }
    }
    results.sort((a, b) => b.score - a.score);
    return results.slice(0, 5).map((r) => r.file);
  }
  // Чтение файла как base64 для изображений
  async readFileAsBase64(file) {
    const arrayBuffer = await this.app.vault.readBinary(file);
    const uint8Array = new Uint8Array(arrayBuffer);
    let binary = "";
    for (let i = 0; i < uint8Array.byteLength; i++) {
      binary += String.fromCharCode(uint8Array[i]);
    }
    return btoa(binary);
  }
  // Определение MIME типа по расширению
  getMimeType(extension) {
    const mimeTypes = {
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "webp": "image/webp",
      "svg": "image/svg+xml",
      "bmp": "image/bmp"
    };
    return mimeTypes[extension.toLowerCase()] || "image/png";
  }
  // Проверка, является ли файл изображением
  isImageFile(file) {
    const imageExtensions = ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp"];
    return imageExtensions.includes(file.extension.toLowerCase());
  }
};
var ChatSidebarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.attachedFiles = [];
    this.commandHistory = [];
    this.historyIndex = -1;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Doc Summarize Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("doc-summarize-sidebar");
    const headerEl = container.createDiv({ cls: "doc-summarize-sidebar-header" });
    const titleEl = headerEl.createDiv({ cls: "doc-summarize-sidebar-title" });
    (0, import_obsidian.setIcon)(titleEl.createSpan(), "message-square");
    titleEl.createSpan({ text: " Doc Summarize" });
    const headerActions = headerEl.createDiv({ cls: "doc-summarize-header-actions" });
    const saveBtn = headerActions.createEl("button", { cls: "doc-summarize-icon-btn", attr: { "aria-label": "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0447\u0430\u0442 \u043A\u0430\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0443" } });
    (0, import_obsidian.setIcon)(saveBtn, "save");
    saveBtn.onclick = () => this.saveChatAsNote();
    const clearBtn = headerActions.createEl("button", { cls: "doc-summarize-icon-btn", attr: { "aria-label": "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u0447\u0430\u0442" } });
    (0, import_obsidian.setIcon)(clearBtn, "trash-2");
    clearBtn.onclick = () => this.clearChat();
    const addCurrentBtn = headerActions.createEl("button", { cls: "doc-summarize-icon-btn", attr: { "aria-label": "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0442\u0435\u043A\u0443\u0449\u0443\u044E \u0437\u0430\u043C\u0435\u0442\u043A\u0443" } });
    (0, import_obsidian.setIcon)(addCurrentBtn, "file-plus");
    addCurrentBtn.onclick = () => this.addCurrentNote();
    this.attachmentsEl = container.createDiv({ cls: "doc-summarize-attachments" });
    this.messagesEl = container.createDiv({ cls: "doc-summarize-messages" });
    this.addMessageToUI("system", "\u{1F44B} \u041F\u0440\u0438\u0432\u0435\u0442! \u042F \u043C\u043E\u0433\u0443 \u043F\u043E\u043C\u043E\u0447\u044C \u0441 \u0432\u0430\u0448\u0438\u043C\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438, \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F\u043C\u0438 \u0438 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u043C\u0438.\n\n\u{1F4CE} \u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u0435 \u0444\u0430\u0439\u043B\u044B \u043A\u043D\u043E\u043F\u043A\u0430\u043C\u0438 \u043D\u0438\u0436\u0435 \u0438\u043B\u0438 \u043F\u0435\u0440\u0435\u0442\u0430\u0449\u0438\u0442\u0435 \u0438\u0445 \u0441\u044E\u0434\u0430.\n\n\u{1F4A1} \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435 \u043A\u043D\u043E\u043F\u043A\u0443 \u2795 \u0447\u0442\u043E\u0431\u044B \u0434\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0442\u0435\u043A\u0443\u0449\u0443\u044E \u0437\u0430\u043C\u0435\u0442\u043A\u0443.");
    const addFilesPanel = container.createDiv({ cls: "doc-summarize-add-files-panel" });
    const addNoteBtn = addFilesPanel.createEl("button", { cls: "doc-summarize-add-file-btn" });
    (0, import_obsidian.setIcon)(addNoteBtn, "file-text");
    addNoteBtn.createSpan({ text: " \u0417\u0430\u043C\u0435\u0442\u043A\u0430" });
    addNoteBtn.onclick = () => this.showNoteSelector();
    const addImageBtn = addFilesPanel.createEl("button", { cls: "doc-summarize-add-file-btn" });
    (0, import_obsidian.setIcon)(addImageBtn, "image");
    addImageBtn.createSpan({ text: " \u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435" });
    addImageBtn.onclick = () => this.showImageSelector();
    const addFromVaultBtn = addFilesPanel.createEl("button", { cls: "doc-summarize-add-file-btn" });
    (0, import_obsidian.setIcon)(addFromVaultBtn, "folder-open");
    addFromVaultBtn.createSpan({ text: " \u0418\u0437 vault" });
    addFromVaultBtn.onclick = () => this.showFileSelector();
    const addFolderBtn = addFilesPanel.createEl("button", { cls: "doc-summarize-add-file-btn" });
    (0, import_obsidian.setIcon)(addFolderBtn, "folder");
    addFolderBtn.createSpan({ text: "\u041F\u0430\u043F\u043A\u0443" });
    addFolderBtn.onclick = () => this.showFolderSelector();
    const addAllBtn = addFilesPanel.createEl("button", { cls: "doc-summarize-add-file-btn doc-summarize-add-all-btn" });
    (0, import_obsidian.setIcon)(addAllBtn, "files");
    addAllBtn.createSpan({ text: " \u0412\u0441\u0435 \u0444\u0430\u0439\u043B\u044B" });
    addAllBtn.onclick = () => this.addAllNotes();
    const inputArea = container.createDiv({ cls: "doc-summarize-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      placeholder: "\u0417\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441 \u043E \u043F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D\u043D\u044B\u0445 \u0444\u0430\u0439\u043B\u0430\u0445..."
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      } else if (e.key === "ArrowUp" && this.historyIndex === -1 && this.inputEl.value === "") {
        if (this.commandHistory.length > 0) {
          this.historyIndex = this.commandHistory.length - 1;
          this.inputEl.value = this.commandHistory[this.historyIndex];
        }
        e.preventDefault();
      } else if (e.key === "ArrowUp" && this.historyIndex > 0) {
        this.historyIndex--;
        this.inputEl.value = this.commandHistory[this.historyIndex];
        e.preventDefault();
      } else if (e.key === "ArrowDown" && this.historyIndex >= 0 && this.historyIndex < this.commandHistory.length - 1) {
        this.historyIndex++;
        this.inputEl.value = this.commandHistory[this.historyIndex];
        e.preventDefault();
      } else if (e.key === "ArrowDown" && this.historyIndex === this.commandHistory.length - 1) {
        this.historyIndex = -1;
        this.inputEl.value = "";
        e.preventDefault();
      }
    });
    this.sendBtn = inputArea.createEl("button", {
      cls: "doc-summarize-send-btn"
    });
    (0, import_obsidian.setIcon)(this.sendBtn, "send");
    this.sendBtn.onclick = () => this.sendMessage();
    this.setupDragAndDrop(container);
  }
  setupDragAndDrop(container) {
    container.addEventListener("dragover", (e) => {
      e.preventDefault();
      container.addClass("doc-summarize-dragover");
    });
    container.addEventListener("dragleave", () => {
      container.removeClass("doc-summarize-dragover");
    });
    container.addEventListener("drop", async (e) => {
      var _a, _b;
      e.preventDefault();
      container.removeClass("doc-summarize-dragover");
      const files = (_a = e.dataTransfer) == null ? void 0 : _a.files;
      if (files && files.length > 0) {
        for (let i = 0; i < files.length; i++) {
          await this.addExternalFile(files[i]);
        }
      }
      const text = (_b = e.dataTransfer) == null ? void 0 : _b.getData("text/plain");
      if (text) {
        const file = this.app.vault.getAbstractFileByPath(text);
        if (file instanceof import_obsidian.TFile) {
          await this.attachFile(file);
        }
      }
    });
  }
  async addExternalFile(file) {
    if (this.attachedFiles.some((f) => f.name === file.name)) {
      new import_obsidian.Notice(`\u0424\u0430\u0439\u043B "${file.name}" \u0443\u0436\u0435 \u043F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D`);
      return;
    }
    const reader = new FileReader();
    reader.onload = async () => {
      const base64 = reader.result.split(",")[1];
      const isImage = file.type.startsWith("image/");
      const attached = {
        name: file.name,
        type: isImage ? "image" : "file",
        path: file.name,
        base64: isImage ? base64 : void 0,
        mimeType: file.type,
        content: isImage ? void 0 : atob(base64)
      };
      this.attachedFiles.push(attached);
      this.updateAttachmentsUI();
    };
    reader.readAsDataURL(file);
  }
  async addCurrentNote() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view && view.file) {
      await this.attachFile(view.file);
      new import_obsidian.Notice(`\u0414\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0437\u0430\u043C\u0435\u0442\u043A\u0430: ${view.file.basename}`);
    } else {
      new import_obsidian.Notice("\u041E\u0442\u043A\u0440\u043E\u0439\u0442\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0443 \u0434\u043B\u044F \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0438\u044F");
    }
  }
  async attachFile(file) {
    if (this.attachedFiles.some((f) => f.path === file.path || f.name === file.basename)) {
      new import_obsidian.Notice("\u0424\u0430\u0439\u043B \u0443\u0436\u0435 \u043F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D");
      return;
    }
    if (this.plugin.isImageFile(file)) {
      const base64 = await this.plugin.readFileAsBase64(file);
      const mimeType = this.plugin.getMimeType(file.extension);
      this.attachedFiles.push({
        name: file.basename,
        type: "image",
        path: file.path,
        base64,
        mimeType
      });
    } else {
      const content = await this.app.vault.read(file);
      this.attachedFiles.push({
        name: file.basename,
        type: "note",
        path: file.path,
        content
      });
    }
    this.updateAttachmentsUI();
  }
  updateAttachmentsUI() {
    this.attachmentsEl.empty();
    if (this.attachedFiles.length === 0) {
      return;
    }
    const label = this.attachmentsEl.createDiv({ cls: "doc-summarize-attachments-label" });
    label.setText(`\u{1F4CE} \u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043E (${this.attachedFiles.length}):`);
    const list = this.attachmentsEl.createDiv({ cls: "doc-summarize-attachments-list" });
    for (const file of this.attachedFiles) {
      const chip = list.createDiv({ cls: "doc-summarize-attachment-chip" });
      const icon = file.type === "image" ? "image" : "file-text";
      (0, import_obsidian.setIcon)(chip.createSpan({ cls: "doc-summarize-attachment-icon" }), icon);
      chip.createSpan({ text: file.name, cls: "doc-summarize-attachment-name" });
      const removeBtn = chip.createSpan({ cls: "doc-summarize-attachment-remove" });
      (0, import_obsidian.setIcon)(removeBtn, "x");
      removeBtn.onclick = () => {
        this.attachedFiles = this.attachedFiles.filter((f) => f.path !== file.path);
        this.updateAttachmentsUI();
      };
    }
  }
  showNoteSelector() {
    const modal = new NoteSelectorModal(this.app, async (file) => {
      await this.attachFile(file);
    });
    modal.open();
  }
  showImageSelector() {
    const modal = new ImageSelectorModal(this.app, this.plugin, async (file) => {
      await this.attachFile(file);
    });
    modal.open();
  }
  showFileSelector() {
    const modal = new FileSelectorModal(this.app, this.plugin, async (file) => {
      await this.attachFile(file);
    });
    modal.open();
  }
  showFolderSelector() {
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((f) => f.path);
    const modal = new FolderSelectorModal(this.app, async (folderPath) => {
      const files = this.app.vault.getFiles().filter((f) => f.path.startsWith(folderPath + "/") || f.path === folderPath);
      for (const file of files) {
        if (!this.plugin.isImageFile(file)) {
          await this.attachFile(file);
        }
      }
      new import_obsidian.Notice(`\u0414\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043E ${files.length} \u0444\u0430\u0439\u043B\u043E\u0432 \u0438\u0437 \u043F\u0430\u043F\u043A\u0438 ${folderPath}`);
    });
    modal.open();
  }
  async addAllNotes() {
    var _a;
    const files = this.app.vault.getFiles();
    if (files.length === 0) {
      new import_obsidian.Notice("\u041D\u0435\u0442 \u0444\u0430\u0439\u043B\u043E\u0432 \u0432 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0435 (vault)");
      return;
    }
    if (files.length > 50) {
      const confirm = await this.showConfirmModal(
        `\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432\u0441\u0435 ${files.length} \u0444\u0430\u0439\u043B\u043E\u0432?`,
        "\u042D\u0442\u043E \u043C\u043E\u0436\u0435\u0442 \u0437\u0430\u043D\u044F\u0442\u044C \u0432\u0440\u0435\u043C\u044F \u0438 \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u044C \u043C\u043D\u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430 \u043C\u043E\u0434\u0435\u043B\u0438."
      );
      if (!confirm)
        return;
    }
    new import_obsidian.Notice(`\u0414\u043E\u0431\u0430\u0432\u043B\u044F\u044E \u0432\u0441\u0435 \u0444\u0430\u0439\u043B\u044B...`);
    const maxContextLength = this.plugin.settings.maxContextLength;
    const imageExts = ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp"];
    const videoExts = ["mp4", "mov", "avi", "mkv", "webm", "wmv", "flv", "mpeg", "mpg"];
    let textFiles = files.filter((file) => {
      const ext = file.extension.toLowerCase();
      return !imageExts.includes(ext) && !videoExts.includes(ext);
    });
    new import_obsidian.Notice(`\u041D\u0430\u0439\u0434\u0435\u043D\u043E ${textFiles.length} \u0442\u0435\u043A\u0441\u0442\u043E\u0432\u044B\u0445 \u0444\u0430\u0439\u043B\u043E\u0432`);
    if (this.plugin.settings.includeFolders && this.plugin.settings.includeFolders.length > 0) {
      textFiles = textFiles.filter(
        (file) => this.plugin.settings.includeFolders.some((folder) => file.path.startsWith(folder + "/") || file.path === folder)
      );
      new import_obsidian.Notice(`\u041F\u043E\u0441\u043B\u0435 \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u0446\u0438\u0438 \u043F\u043E \u043F\u0430\u043F\u043A\u0430\u043C: ${textFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432`);
    }
    if (this.plugin.settings.includeTags && this.plugin.settings.includeTags.length > 0) {
      textFiles = textFiles.filter((file) => {
        var _a2;
        const cache = this.app.metadataCache.getFileCache(file);
        const tags = ((_a2 = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a2.tags) || [];
        return this.plugin.settings.includeTags.some((tag) => tags.includes(tag));
      });
      new import_obsidian.Notice(`\u041F\u043E\u0441\u043B\u0435 \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u0446\u0438\u0438 \u043F\u043E \u0442\u0435\u0433\u0430\u043C: ${textFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432`);
    }
    if (this.plugin.settings.maxFileAge && this.plugin.settings.maxFileAge > 0) {
      const now = Date.now();
      const maxAgeMs = this.plugin.settings.maxFileAge * 24 * 60 * 60 * 1e3;
      textFiles = textFiles.filter((file) => now - file.stat.mtime < maxAgeMs);
      new import_obsidian.Notice(`\u041F\u043E\u0441\u043B\u0435 \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u0446\u0438\u0438 \u043F\u043E \u0432\u043E\u0437\u0440\u0430\u0441\u0442\u0443: ${textFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432`);
    }
    textFiles.sort((a, b) => b.stat.mtime - a.stat.mtime);
    this.attachedFiles = [];
    if (this.plugin.settings.useFileIndex) {
      let indexContent = "=== \u0418\u041D\u0414\u0415\u041A\u0421 \u0424\u0410\u0419\u041B\u041E\u0412 VAULT ===\n\n";
      let filesToIndex = textFiles;
      if (this.plugin.settings.maxIndexFiles && this.plugin.settings.maxIndexFiles > 0) {
        filesToIndex = textFiles.slice(0, this.plugin.settings.maxIndexFiles);
      }
      const baseInfoPerFile = 100;
      const totalBaseInfo = filesToIndex.length * baseInfoPerFile;
      const availableForPreview = Math.max(0, maxContextLength - totalBaseInfo - 200);
      const previewLengthPerFile = Math.floor(availableForPreview / filesToIndex.length) || 50;
      for (const file of filesToIndex) {
        let content = "";
        try {
          content = await this.app.vault.cachedRead(file);
        } catch (e) {
          continue;
        }
        const size = content.length;
        const preview = content.substring(0, previewLengthPerFile) + (content.length > previewLengthPerFile ? "..." : "");
        const cache = this.app.metadataCache.getFileCache(file);
        const tags = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) || [];
        const keywords = tags.length > 0 ? `\u0422\u0435\u0433\u0438: ${tags.join(", ")}` : "";
        indexContent += `\u{1F4C4} [[${file.path.replace(/\.md$/, "")}]]
`;
        indexContent += `\u0420\u0430\u0437\u043C\u0435\u0440: ${size} \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432
`;
        if (keywords)
          indexContent += `${keywords}
`;
        if (previewLengthPerFile > 10)
          indexContent += `\u041F\u0440\u0435\u0432\u044C\u044E: ${preview}
`;
        indexContent += `
`;
        if (indexContent.length > maxContextLength - 100) {
          indexContent += "[\u0418\u043D\u0434\u0435\u043A\u0441 \u043E\u0431\u0440\u0435\u0437\u0430\u043D - \u043D\u0435\u0434\u043E\u0441\u0442\u0430\u0442\u043E\u0447\u043D\u043E \u043C\u0435\u0441\u0442\u0430]\n";
          break;
        }
      }
      this.attachedFiles.push({
        name: "\u0418\u043D\u0434\u0435\u043A\u0441 \u0444\u0430\u0439\u043B\u043E\u0432",
        type: "note",
        path: "vault-index",
        content: indexContent
      });
      this.addMessageToUI("system", `\u{1F4CB} **\u0418\u043D\u0434\u0435\u043A\u0441 \u0444\u0430\u0439\u043B\u043E\u0432 \u0441\u043E\u0437\u0434\u0430\u043D**

${indexContent}`);
      this.messages.push({ role: "system", content: `\u{1F4CB} **\u0418\u043D\u0434\u0435\u043A\u0441 \u0444\u0430\u0439\u043B\u043E\u0432 \u0441\u043E\u0437\u0434\u0430\u043D**

${indexContent}` });
    } else {
      let totalLength = 0;
      for (const file of textFiles) {
        let content = "";
        try {
          content = await this.app.vault.cachedRead(file);
        } catch (e) {
          continue;
        }
        if (this.attachedFiles.some((f) => f.path === file.path || f.name === file.basename)) {
          continue;
        }
        const remainingLength = maxContextLength - totalLength;
        if (remainingLength <= 0) {
          break;
        }
        let truncatedContent = content;
        if (content.length > remainingLength) {
          truncatedContent = content.substring(0, remainingLength - 100);
          truncatedContent += "\n\n[\u0422\u0435\u043A\u0441\u0442 \u043E\u0431\u0440\u0435\u0437\u0430\u043D \u0434\u043B\u044F \u044D\u043A\u043E\u043D\u043E\u043C\u0438\u0438 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430]";
        }
        this.attachedFiles.push({
          name: file.basename,
          type: file.extension === "md" ? "note" : "file",
          path: file.path,
          content: truncatedContent
        });
        totalLength += truncatedContent.length;
      }
    }
    this.updateAttachmentsUI();
    if (this.attachedFiles.length === 0) {
      new import_obsidian.Notice("\u041D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u043E \u043F\u043E\u0434\u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u0444\u0430\u0439\u043B\u043E\u0432 \u0434\u043B\u044F \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0438\u044F. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0444\u0438\u043B\u044C\u0442\u0440\u043E\u0432.");
    } else {
      const totalSize = this.attachedFiles.reduce((sum, f) => {
        var _a2;
        return sum + (((_a2 = f.content) == null ? void 0 : _a2.length) || 0);
      }, 0);
      new import_obsidian.Notice(`\u2705 \u0414\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043E ${this.attachedFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432 (${Math.round(totalSize / 1024)} \u041A\u0411)`);
    }
  }
  async showConfirmModal(title, message) {
    return new Promise((resolve) => {
      const modal = new ConfirmModal(this.app, title, message, resolve);
      modal.open();
    });
  }
  clearChat() {
    this.messages = [];
    this.attachedFiles = [];
    this.messagesEl.empty();
    this.updateAttachmentsUI();
    this.addMessageToUI("system", "\u{1F4AC} \u0427\u0430\u0442 \u043E\u0447\u0438\u0449\u0435\u043D. \u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u0435 \u0444\u0430\u0439\u043B\u044B \u0438 \u0437\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441.");
  }
  async saveChatAsNote() {
    if (this.messages.length === 0) {
      new import_obsidian.Notice("\u0427\u0430\u0442 \u043F\u0443\u0441\u0442\u043E\u0439, \u043D\u0435\u0447\u0435\u0433\u043E \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C");
      return;
    }
    try {
      let content = "# \u0427\u0430\u0442 \u0441 Doc Summarize\n\n";
      content += `**\u0414\u0430\u0442\u0430:** ${new Date().toLocaleString()}

`;
      if (this.attachedFiles.length > 0) {
        content += "## \u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D\u043D\u044B\u0435 \u0444\u0430\u0439\u043B\u044B\n\n";
        for (const file of this.attachedFiles) {
          content += `- [[${file.name}]]
`;
        }
        content += "\n";
      }
      content += "## \u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u044F\n\n";
      for (const message of this.messages) {
        if (message.role === "system") {
          content += `**\u0421\u0438\u0441\u0442\u0435\u043C\u0430:** ${message.content}

`;
        } else if (message.role === "user") {
          content += `**\u0412\u044B:** ${message.content}

`;
        } else if (message.role === "assistant") {
          content += `**AI:** ${message.content}

`;
        }
      }
      const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
      const fileName = `Chat-${timestamp}.md`;
      await this.app.vault.create(fileName, content);
      new import_obsidian.Notice(`\u0427\u0430\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0451\u043D \u043A\u0430\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0430: ${fileName}`);
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0438 \u0447\u0430\u0442\u0430:", error);
      new import_obsidian.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0438 \u0447\u0430\u0442\u0430");
    }
  }
  async sendMessage() {
    const question = this.inputEl.value.trim();
    if (!question)
      return;
    this.commandHistory.push(question);
    if (this.commandHistory.length > 50) {
      this.commandHistory.shift();
    }
    this.historyIndex = -1;
    this.inputEl.disabled = true;
    this.sendBtn.disabled = true;
    this.addMessageToUI("user", question);
    this.inputEl.value = "";
    let context = "";
    const images = [];
    const textFiles = this.attachedFiles.filter((f) => f.type !== "image" && f.content);
    if (this.plugin.settings.useMapReduce && textFiles.length > 0) {
      const summaries = [];
      for (const file of textFiles) {
        if (file.content) {
          const summary = await this.plugin.getSummary(file.content);
          if (summary) {
            summaries.push(`=== \u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F ${file.name} ===
${summary}`);
          }
        }
      }
      const combinedSummaries = summaries.join("\n\n");
      const maxSummariesLength = this.plugin.settings.maxContextLength - question.length - 500;
      if (combinedSummaries.length > maxSummariesLength) {
        context = combinedSummaries.substring(0, maxSummariesLength) + "\n\n[\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u043E\u0431\u0440\u0435\u0437\u0430\u043D\u044B \u0434\u043B\u044F \u044D\u043A\u043E\u043D\u043E\u043C\u0438\u0438 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430]";
      } else {
        context = combinedSummaries;
      }
    } else {
      const maxContextForDocs = this.plugin.settings.maxContextLength - question.length;
      const charsPerFile = textFiles.length > 0 ? Math.floor(maxContextForDocs / textFiles.length) : 0;
      if (charsPerFile <= 0 && textFiles.length > 0) {
        new import_obsidian.Notice(`\u0421\u043B\u0438\u0448\u043A\u043E\u043C \u043C\u043D\u043E\u0433\u043E \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432 (${textFiles.length}) \u0434\u043B\u044F \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430 ${this.plugin.settings.maxContextLength} \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432. \u0423\u043C\u0435\u043D\u044C\u0448\u0438\u0442\u0435 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432 \u0438\u043B\u0438 \u0443\u0432\u0435\u043B\u0438\u0447\u044C\u0442\u0435 \u043B\u0438\u043C\u0438\u0442 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430.`);
        return;
      }
      for (const file of this.attachedFiles) {
        if (file.type === "image" && file.base64) {
          images.push(`data:${file.mimeType};base64,${file.base64}`);
          context += `

[\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435: ${file.name}]`;
        } else if (file.content) {
          const truncatedContent = file.content.length > charsPerFile ? file.content.substring(0, charsPerFile) + "\n\n[\u0422\u0435\u043A\u0441\u0442 \u043E\u0431\u0440\u0435\u0437\u0430\u043D \u0434\u043B\u044F \u044D\u043A\u043E\u043D\u043E\u043C\u0438\u0438 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430]" : file.content;
          context += `

=== ${file.name} ===
${truncatedContent}`;
        }
      }
    }
    const loadingEl = this.messagesEl.createDiv({ cls: "doc-summarize-loading" });
    loadingEl.setText("\u{1F914} \u0414\u0443\u043C\u0430\u044E...");
    this.scrollToBottom();
    try {
      const systemMessage = context ? `${this.plugin.settings.questionPrompt}

\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D\u043D\u044B\u0435 \u0444\u0430\u0439\u043B\u044B:${context}` : this.plugin.settings.questionPrompt;
      const messages = [
        { role: "system", content: systemMessage },
        ...this.messages.filter((m) => m.role !== "system"),
        { role: "user", content: question, images: images.length > 0 ? images : void 0 }
      ];
      const assistantMessageEl = this.messagesEl.createDiv({
        cls: `doc-summarize-message assistant`
      });
      let currentResponse = "";
      const response = await this.plugin.sendToLMStudio(messages);
      currentResponse = response;
      const processedContent = currentResponse.replace(
        /\[\[(.*?)\]\]/g,
        '<span class="doc-summarize-note-ref" data-note="$1">$1</span>'
      );
      assistantMessageEl.innerHTML = processedContent;
      assistantMessageEl.querySelectorAll(".doc-summarize-note-ref").forEach((el) => {
        el.addEventListener("click", () => {
          const noteName = el.getAttribute("data-note");
          if (noteName) {
            this.app.workspace.openLinkText(noteName, "");
          }
        });
      });
      loadingEl.remove();
      this.messages.push({ role: "user", content: question });
      this.messages.push({ role: "assistant", content: response });
    } catch (error) {
      loadingEl.remove();
      this.addMessageToUI("error", "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0438 \u043E\u0442\u0432\u0435\u0442\u0430. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio.");
    }
    this.inputEl.disabled = false;
    this.sendBtn.disabled = false;
    this.inputEl.focus();
  }
  addMessageToUI(role, content) {
    const messageEl = this.messagesEl.createDiv({
      cls: `doc-summarize-message ${role}`
    });
    let processedContent = content;
    if (role === "assistant" || role === "system") {
      processedContent = this.renderMarkdown(content);
    } else {
      processedContent = content.replace(
        /\[\[(.*?)\]\]/g,
        '<span class="doc-summarize-note-ref" data-note="$1">$1</span>'
      );
    }
    messageEl.innerHTML = processedContent;
    if (role === "assistant") {
      const copyBtn = messageEl.createEl("button", {
        cls: "doc-summarize-copy-btn",
        attr: { "aria-label": "\u041A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435" }
      });
      (0, import_obsidian.setIcon)(copyBtn, "copy");
      copyBtn.onclick = async () => {
        await navigator.clipboard.writeText(content);
        new import_obsidian.Notice("\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435 \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u043E");
      };
    }
    messageEl.querySelectorAll(".doc-summarize-note-ref").forEach((el) => {
      el.addEventListener("click", () => {
        const noteName = el.getAttribute("data-note");
        if (noteName) {
          this.app.workspace.openLinkText(noteName, "");
        }
      });
    });
    this.scrollToBottom();
  }
  // Простой рендерер markdown
  renderMarkdown(text) {
    return text.replace(/\*\*([A-Z]{2}\d+[A-Z]\d+)\*\*/g, "[[$1]]").replace(/^### (.*$)/gm, (match, content) => `<h3>${content.replace(/\*\*(.*?)\*\*/g, "[[$1]]")}</h3>`).replace(/^## (.*$)/gm, (match, content) => `<h2>${content.replace(/\*\*(.*?)\*\*/g, "[[$1]]")}</h2>`).replace(/^# (.*$)/gm, (match, content) => `<h1>${content.replace(/\*\*(.*?)\*\*/g, "[[$1]]")}</h1>`).replace(/\*\*\*(.*?)\*\*\*/g, "<strong><em>$1</em></strong>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/\*(.*?)\*/g, "<em>$1</em>").replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/^\* (.*$)/gm, "<li>$1</li>").replace(/^\d+\. (.*$)/gm, "<li>$1</li>").replace(/^> (.*$)/gm, "<blockquote>$1</blockquote>").replace(/^---$/gm, "<hr>").replace(/^___$/gm, "<hr>").replace(/^\*\*\*$/gm, "<hr>").replace(/\[\[(.*?)\]\]/g, '<span class="doc-summarize-note-ref" data-note="$1">$1</span>');
  }
  scrollToBottom() {
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  async onClose() {
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, title, message, onResult) {
    super(app);
    this.title = title;
    this.message = message;
    this.onResult = onResult;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message, cls: "doc-summarize-confirm-message" });
    const buttonsEl = contentEl.createDiv({ cls: "doc-summarize-confirm-buttons" });
    const cancelBtn = buttonsEl.createEl("button", { text: "\u041E\u0442\u043C\u0435\u043D\u0430" });
    cancelBtn.onclick = () => {
      this.onResult(false);
      this.close();
    };
    const confirmBtn = buttonsEl.createEl("button", { text: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.onResult(true);
      this.close();
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var NoteSelectorModal = class extends import_obsidian.Modal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0443" });
    const searchInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u041F\u043E\u0438\u0441\u043A \u0437\u0430\u043C\u0435\u0442\u043E\u043A...",
      cls: "doc-summarize-search-input"
    });
    const listEl = contentEl.createDiv({ cls: "doc-summarize-file-list" });
    const files = this.app.vault.getMarkdownFiles().sort(
      (a, b) => b.stat.mtime - a.stat.mtime
    );
    const renderFiles = (filter = "") => {
      listEl.empty();
      const filtered = filter ? files.filter((f) => f.basename.toLowerCase().includes(filter.toLowerCase())) : files.slice(0, 20);
      for (const file of filtered) {
        const item = listEl.createDiv({ cls: "doc-summarize-file-item" });
        (0, import_obsidian.setIcon)(item.createSpan(), "file-text");
        item.createSpan({ text: ` ${file.basename}` });
        item.onclick = () => {
          this.onChoose(file);
          this.close();
        };
      }
    };
    searchInput.addEventListener("input", () => {
      renderFiles(searchInput.value);
    });
    renderFiles();
    searchInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImageSelectorModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onChoose) {
    super(app);
    this.plugin = plugin;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435" });
    const listEl = contentEl.createDiv({ cls: "doc-summarize-file-list doc-summarize-image-grid" });
    const files = this.app.vault.getFiles().filter((f) => this.plugin.isImageFile(f)).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, 30);
    for (const file of files) {
      const item = listEl.createDiv({ cls: "doc-summarize-image-item" });
      const imgContainer = item.createDiv({ cls: "doc-summarize-image-preview-container" });
      const resourcePath = this.app.vault.getResourcePath(file);
      imgContainer.createEl("img", {
        attr: { src: resourcePath },
        cls: "doc-summarize-image-preview-thumb"
      });
      item.createDiv({ text: file.basename, cls: "doc-summarize-image-name" });
      item.onclick = () => {
        this.onChoose(file);
        this.close();
      };
    }
    if (files.length === 0) {
      listEl.createDiv({ text: "\u041D\u0435\u0442 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439 \u0432 vault", cls: "doc-summarize-empty-message" });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FileSelectorModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onChoose) {
    super(app);
    this.plugin = plugin;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0444\u0430\u0439\u043B" });
    const searchInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u041F\u043E\u0438\u0441\u043A \u0444\u0430\u0439\u043B\u043E\u0432...",
      cls: "doc-summarize-search-input"
    });
    const listEl = contentEl.createDiv({ cls: "doc-summarize-file-list" });
    const files = this.app.vault.getFiles().sort((a, b) => b.stat.mtime - a.stat.mtime);
    const renderFiles = (filter = "") => {
      listEl.empty();
      const filtered = filter ? files.filter((f) => f.basename.toLowerCase().includes(filter.toLowerCase())) : files.slice(0, 30);
      for (const file of filtered) {
        const item = listEl.createDiv({ cls: "doc-summarize-file-item" });
        const icon = this.plugin.isImageFile(file) ? "image" : "file-text";
        (0, import_obsidian.setIcon)(item.createSpan(), icon);
        item.createSpan({ text: ` ${file.name}` });
        item.onclick = () => {
          this.onChoose(file);
          this.close();
        };
      }
    };
    searchInput.addEventListener("input", () => {
      renderFiles(searchInput.value);
    });
    renderFiles();
    searchInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SummaryModal = class extends import_obsidian.Modal {
  constructor(app, plugin, content, title) {
    super(app);
    this.plugin = plugin;
    this.content = content;
    this.title = title;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: `\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F: ${this.title}` });
    const loadingEl = contentEl.createDiv({ cls: "doc-summarize-loading" });
    loadingEl.setText("\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438...");
    try {
      const summary = await this.plugin.getSummary(this.content);
      loadingEl.remove();
      if (summary) {
        const resultEl = contentEl.createDiv({ cls: "doc-summarize-result" });
        resultEl.innerHTML = this.formatMarkdown(summary);
        const actionsEl = contentEl.createDiv({ cls: "doc-summarize-actions" });
        const copyBtn = actionsEl.createEl("button", { text: "\u{1F4CB} \u041A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C" });
        copyBtn.onclick = () => {
          navigator.clipboard.writeText(summary);
          new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0430 \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430");
        };
        const insertBtn = actionsEl.createEl("button", { text: "\u{1F4DD} \u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044C \u0432 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442" });
        insertBtn.onclick = () => {
          const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
          if (view) {
            const editor = view.editor;
            const cursor = editor.getCursor();
            editor.replaceRange(
              `

---
## \u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F

${summary}

---
`,
              cursor
            );
            new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u044F \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442");
            this.close();
          }
        };
      }
    } catch (error) {
      loadingEl.remove();
      const errorEl = contentEl.createDiv({ cls: "doc-summarize-message error" });
      errorEl.setText("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0438 \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio.");
    }
  }
  formatMarkdown(text) {
    return text.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/\*(.*?)\*/g, "<em>$1</em>").replace(/^### (.*$)/gm, "<h3>$1</h3>").replace(/^## (.*$)/gm, "<h2>$1</h2>").replace(/^# (.*$)/gm, "<h1>$1</h1>").replace(/^- (.*$)/gm, "<li>$1</li>").replace(/\n/g, "<br>");
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ChatModal = class extends import_obsidian.Modal {
  constructor(app, plugin, content, file) {
    super(app);
    this.messages = [];
    this.attachedFiles = [];
    this.commandHistory = [];
    this.historyIndex = -1;
    this.plugin = plugin;
    this.content = content;
    this.file = file;
  }
  async onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    if (this.file) {
      this.attachedFiles = [{
        name: this.file.basename,
        type: "note",
        path: this.file.path,
        content: this.content
      }];
    }
    contentEl.createEl("h2", { text: `\u0412\u043E\u043F\u0440\u043E\u0441\u044B \u043E: ${((_a = this.file) == null ? void 0 : _a.basename) || "\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442"}` });
    const saveBtn = contentEl.createEl("button", {
      cls: "doc-summarize-save-chat-btn",
      text: "\u{1F4BE} \u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0447\u0430\u0442 \u043A\u0430\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0443"
    });
    saveBtn.onclick = () => this.saveChatAsNote();
    const contextInfo = contentEl.createDiv({ cls: "doc-summarize-context-info" });
    contextInfo.setText(`\u{1F4C4} \u041A\u043E\u043D\u0442\u0435\u043A\u0441\u0442: ${this.content.length} \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432`);
    let linkedContent = "";
    if (this.plugin.settings.includeLinkedNotes && this.file) {
      const linkedNotes = await this.plugin.getLinkedNotes(
        this.file,
        this.plugin.settings.maxLinkedNotesDepth
      );
      if (linkedNotes.size > 0) {
        linkedContent = "\n\n--- \u0421\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 ---\n\n" + Array.from(linkedNotes.values()).join("\n\n");
        contextInfo.setText(
          `\u{1F4C4} \u041A\u043E\u043D\u0442\u0435\u043A\u0441\u0442: ${this.content.length} \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432 | \u{1F517} \u0421\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438: ${linkedNotes.size}`
        );
      }
    }
    const fullContext = this.content + linkedContent;
    this.messages = [
      {
        role: "system",
        content: `${this.plugin.settings.questionPrompt}

\u041A\u043E\u043D\u0442\u0435\u043A\u0441\u0442 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430:

${fullContext}`
      }
    ];
    const chatContainer = contentEl.createDiv({ cls: "doc-summarize-chat-container" });
    this.messagesEl = chatContainer.createDiv({ cls: "doc-summarize-messages" });
    const inputArea = chatContainer.createDiv({ cls: "doc-summarize-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      placeholder: "\u0417\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441 \u043E \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0435..."
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      } else if (e.key === "ArrowUp" && this.historyIndex === -1 && this.inputEl.value === "") {
        if (this.commandHistory.length > 0) {
          this.historyIndex = this.commandHistory.length - 1;
          this.inputEl.value = this.commandHistory[this.historyIndex];
        }
        e.preventDefault();
      } else if (e.key === "ArrowUp" && this.historyIndex > 0) {
        this.historyIndex--;
        this.inputEl.value = this.commandHistory[this.historyIndex];
        e.preventDefault();
      } else if (e.key === "ArrowDown" && this.historyIndex >= 0 && this.historyIndex < this.commandHistory.length - 1) {
        this.historyIndex++;
        this.inputEl.value = this.commandHistory[this.historyIndex];
        e.preventDefault();
      } else if (e.key === "ArrowDown" && this.historyIndex === this.commandHistory.length - 1) {
        this.historyIndex = -1;
        this.inputEl.value = "";
        e.preventDefault();
      }
    });
    this.sendBtn = inputArea.createEl("button", {
      text: "\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C",
      cls: "doc-summarize-send-btn"
    });
    this.sendBtn.onclick = () => this.sendMessage();
    this.inputEl.focus();
  }
  async sendMessage() {
    const question = this.inputEl.value.trim();
    if (!question)
      return;
    this.commandHistory.push(question);
    if (this.commandHistory.length > 50) {
      this.commandHistory.shift();
    }
    this.historyIndex = -1;
    this.inputEl.disabled = true;
    this.sendBtn.disabled = true;
    this.addMessageToUI("user", question);
    this.messages.push({ role: "user", content: question });
    this.inputEl.value = "";
    const loadingEl = this.messagesEl.createDiv({ cls: "doc-summarize-loading" });
    loadingEl.setText("\u{1F914} \u0414\u0443\u043C\u0430\u044E...");
    this.scrollToBottom();
    try {
      const response = await this.plugin.sendToLMStudio(this.messages);
      loadingEl.remove();
      this.addMessageToUI("assistant", response);
      this.messages.push({ role: "assistant", content: response });
    } catch (error) {
      loadingEl.remove();
      this.addMessageToUI("error", "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0438 \u043E\u0442\u0432\u0435\u0442\u0430. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio.");
    }
    this.inputEl.disabled = false;
    this.sendBtn.disabled = false;
    this.inputEl.focus();
  }
  async saveChatAsNote() {
    var _a, _b;
    if (this.messages.length === 0) {
      new import_obsidian.Notice("\u0427\u0430\u0442 \u043F\u0443\u0441\u0442\u043E\u0439, \u043D\u0435\u0447\u0435\u0433\u043E \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C");
      return;
    }
    try {
      let content = "# \u0427\u0430\u0442 \u0441 Doc Summarize\n\n";
      content += `**\u0414\u0430\u0442\u0430:** ${new Date().toLocaleString()}

`;
      content += `**\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442:** [[${((_a = this.file) == null ? void 0 : _a.basename) || "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u044B\u0439 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442"}]]

`;
      if (this.attachedFiles.length > 0) {
        content += "## \u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0451\u043D\u043D\u044B\u0435 \u0444\u0430\u0439\u043B\u044B\n\n";
        for (const file of this.attachedFiles) {
          content += `- [[${file.name}]]
`;
        }
        content += "\n";
      }
      content += "## \u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u044F\n\n";
      for (const message of this.messages) {
        if (message.role === "system") {
          content += `**\u0421\u0438\u0441\u0442\u0435\u043C\u0430:** ${message.content}

`;
        } else if (message.role === "user") {
          content += `**\u0412\u044B:** ${message.content}

`;
        } else if (message.role === "assistant") {
          content += `**AI:** ${message.content}

`;
        }
      }
      const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
      const fileName = `Chat-${((_b = this.file) == null ? void 0 : _b.basename) || "Document"}-${timestamp}.md`;
      await this.app.vault.create(fileName, content);
      new import_obsidian.Notice(`\u0427\u0430\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0451\u043D \u043A\u0430\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0430: ${fileName}`);
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0438 \u0447\u0430\u0442\u0430:", error);
      new import_obsidian.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0438 \u0447\u0430\u0442\u0430");
    }
  }
  renderMarkdown(content) {
    const patentRegex = /\*\*([A-Z]{2}\d+[A-Z]\d+)\*\*/g;
    content = content.replace(patentRegex, (match, patentNumber) => {
      const country = patentNumber.substring(0, 2);
      let url = "";
      switch (country) {
        case "US":
          url = `https://patents.google.com/patent/${patentNumber}`;
          break;
        case "RU":
          url = `https://patents.google.com/patent/${patentNumber}`;
          break;
        case "CN":
          url = `https://patents.google.com/patent/${patentNumber}`;
          break;
        case "JP":
          url = `https://patents.google.com/patent/${patentNumber}`;
          break;
        default:
          return match;
      }
      return `[${patentNumber}](${url})`;
    });
    return content;
  }
  addMessageToUI(role, content) {
    const messageEl = this.messagesEl.createDiv({
      cls: `doc-summarize-message ${role}`
    });
    let processedContent = this.renderMarkdown(content);
    processedContent = processedContent.replace(
      /\[\[(.*?)\]\]/g,
      '<span class="doc-summarize-note-ref" data-note="$1">$1</span>'
    );
    messageEl.innerHTML = processedContent;
    messageEl.querySelectorAll(".doc-summarize-note-ref").forEach((el) => {
      el.addEventListener("click", () => {
        const noteName = el.getAttribute("data-note");
        if (noteName) {
          this.app.workspace.openLinkText(noteName, "");
        }
      });
    });
    this.scrollToBottom();
  }
  scrollToBottom() {
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImageSummarizeModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: "\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F" });
    const infoEl = contentEl.createDiv({ cls: "doc-summarize-context-info" });
    infoEl.setText("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0438\u0437\u0430. \u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043C\u043E\u0434\u0435\u043B\u044C \u0441 \u043F\u043E\u0434\u0434\u0435\u0440\u0436\u043A\u043E\u0439 vision (\u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440, LLaVA).");
    const inputContainer = contentEl.createDiv();
    const fileInput = inputContainer.createEl("input", {
      type: "file",
      attr: { accept: "image/*" }
    });
    const promptInput = contentEl.createEl("textarea", {
      placeholder: "\u041E\u043F\u0438\u0448\u0438\u0442\u0435, \u0447\u0442\u043E \u0432\u044B \u0445\u043E\u0442\u0438\u0442\u0435 \u0443\u0437\u043D\u0430\u0442\u044C \u043E\u0431 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0438 (\u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E)..."
    });
    promptInput.style.width = "100%";
    promptInput.style.minHeight = "60px";
    promptInput.style.marginTop = "10px";
    const resultEl = contentEl.createDiv({ cls: "doc-summarize-result" });
    resultEl.style.display = "none";
    const analyzeBtn = contentEl.createEl("button", {
      text: "\u0410\u043D\u0430\u043B\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
      cls: "doc-summarize-send-btn"
    });
    analyzeBtn.style.marginTop = "15px";
    analyzeBtn.onclick = async () => {
      var _a;
      const file = (_a = fileInput.files) == null ? void 0 : _a[0];
      if (!file) {
        new import_obsidian.Notice("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435");
        return;
      }
      analyzeBtn.disabled = true;
      analyzeBtn.setText("\u0410\u043D\u0430\u043B\u0438\u0437...");
      try {
        const base64 = await this.fileToBase64(file);
        const prompt = promptInput.value.trim() || "\u041E\u043F\u0438\u0448\u0438 \u044D\u0442\u043E \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u043F\u043E\u0434\u0440\u043E\u0431\u043D\u043E \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435.";
        const messages = [
          {
            role: "user",
            content: prompt,
            images: [`data:${file.type};base64,${base64}`]
          }
        ];
        const response = await this.plugin.sendToLMStudio(messages);
        resultEl.style.display = "block";
        resultEl.setText(response);
      } catch (error) {
        new import_obsidian.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0430\u043D\u0430\u043B\u0438\u0437\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F. \u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044C, \u0447\u0442\u043E \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0435\u0442\u0441\u044F \u043C\u043E\u0434\u0435\u043B\u044C \u0441 \u043F\u043E\u0434\u0434\u0435\u0440\u0436\u043A\u043E\u0439 vision.");
        console.error(error);
      }
      analyzeBtn.disabled = false;
      analyzeBtn.setText("\u0410\u043D\u0430\u043B\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435");
    };
  }
  fileToBase64(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        const base64 = result.split(",")[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var VaultChatModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.messages = [];
    this.relevantNotes = [];
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("doc-summarize-modal");
    contentEl.createEl("h2", { text: "\u0412\u043E\u043F\u0440\u043E\u0441\u044B \u043E \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u0445" });
    const contextInfo = contentEl.createDiv({ cls: "doc-summarize-context-info" });
    contextInfo.setText("\u0417\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441, \u0438 \u044F \u043D\u0430\u0439\u0434\u0443 \u0440\u0435\u043B\u0435\u0432\u0430\u043D\u0442\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u0434\u043B\u044F \u043E\u0442\u0432\u0435\u0442\u0430.");
    const chatContainer = contentEl.createDiv({ cls: "doc-summarize-chat-container" });
    this.messagesEl = chatContainer.createDiv({ cls: "doc-summarize-messages" });
    const inputArea = chatContainer.createDiv({ cls: "doc-summarize-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      placeholder: "\u0417\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441 \u043E \u0432\u0430\u0448\u0438\u0445 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u0445..."
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.sendBtn = inputArea.createEl("button", {
      text: "\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C",
      cls: "doc-summarize-send-btn"
    });
    this.sendBtn.onclick = () => this.sendMessage();
    this.inputEl.focus();
  }
  async sendMessage() {
    const question = this.inputEl.value.trim();
    if (!question)
      return;
    this.inputEl.disabled = true;
    this.sendBtn.disabled = true;
    this.addMessageToUI("user", question);
    this.inputEl.value = "";
    const loadingEl = this.messagesEl.createDiv({ cls: "doc-summarize-loading" });
    loadingEl.setText("\u041F\u043E\u0438\u0441\u043A \u0440\u0435\u043B\u0435\u0432\u0430\u043D\u0442\u043D\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A...");
    this.scrollToBottom();
    try {
      this.relevantNotes = await this.plugin.searchNotes(question);
      let context = "";
      for (const note of this.relevantNotes) {
        const content = await this.app.vault.cachedRead(note);
        context += `

=== [[${note.path.replace(/\.md$/, "")}]] ===
${content.substring(0, 2e3)}`;
      }
      loadingEl.setText("\u{1F914} \u0414\u0443\u043C\u0430\u044E...");
      const messages = [
        {
          role: "system",
          content: `${this.plugin.settings.questionPrompt}

\u0420\u0435\u043B\u0435\u0432\u0430\u043D\u0442\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438:${context}`
        },
        ...this.messages.filter((m) => m.role !== "system"),
        { role: "user", content: question }
      ];
      const response = await this.plugin.sendToLMStudio(messages);
      loadingEl.remove();
      if (this.relevantNotes.length > 0) {
        const notesInfo = `\u{1F4DA} \u041D\u0430\u0439\u0434\u0435\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438: ${this.relevantNotes.map((n) => `[[${n.basename}]]`).join(", ")}`;
        this.addMessageToUI("system", notesInfo);
      }
      this.addMessageToUI("assistant", response);
      this.messages.push({ role: "user", content: question });
      this.messages.push({ role: "assistant", content: response });
    } catch (error) {
      loadingEl.remove();
      this.addMessageToUI("error", "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0438 \u043E\u0442\u0432\u0435\u0442\u0430. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio.");
    }
    this.inputEl.disabled = false;
    this.sendBtn.disabled = false;
    this.inputEl.focus();
  }
  addMessageToUI(role, content) {
    const messageEl = this.messagesEl.createDiv({
      cls: `doc-summarize-message ${role}`
    });
    const processedContent = content.replace(
      /\[\[(.*?)\]\]/g,
      '<span class="doc-summarize-note-ref" data-note="$1">$1</span>'
    );
    messageEl.innerHTML = processedContent;
    messageEl.querySelectorAll(".doc-summarize-note-ref").forEach((el) => {
      el.addEventListener("click", () => {
        const noteName = el.getAttribute("data-note");
        if (noteName) {
          this.app.workspace.openLinkText(noteName, "");
        }
      });
    });
    this.scrollToBottom();
  }
  scrollToBottom() {
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DocSummarizeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.modelDropdown = null;
    this.plugin = plugin;
  }
  async display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("doc-summarize-settings");
    containerEl.createEl("h1", { text: "Doc Summarize - \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438" });
    containerEl.createEl("h2", { text: "\u041F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435 \u043A LM Studio" });
    containerEl.createEl("hr");
    new import_obsidian.Setting(containerEl).setName("URL LM Studio API").setDesc("\u0410\u0434\u0440\u0435\u0441 API LM Studio (\u043E\u0431\u044B\u0447\u043D\u043E http://localhost:1234/v1)").addText(
      (text) => text.setPlaceholder("http://localhost:1234/v1").setValue(this.plugin.settings.lmStudioUrl).onChange(async (value) => {
        this.plugin.settings.lmStudioUrl = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u041C\u043E\u0434\u0435\u043B\u044C LM Studio" });
    const modelSetting = new import_obsidian.Setting(containerEl).setName("\u041C\u043E\u0434\u0435\u043B\u044C").setDesc("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043C\u043E\u0434\u0435\u043B\u044C \u0438\u0437 \u0441\u043F\u0438\u0441\u043A\u0430 \u0434\u043E\u0441\u0442\u0443\u043F\u043D\u044B\u0445 \u0432 LM Studio");
    const modelContainer = modelSetting.controlEl.createDiv({ cls: "doc-summarize-model-container" });
    this.modelDropdown = modelContainer.createEl("select", { cls: "doc-summarize-model-select" });
    const refreshBtn = modelContainer.createEl("button", { text: "\u{1F504}", cls: "doc-summarize-refresh-btn" });
    refreshBtn.setAttribute("aria-label", "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0441\u043F\u0438\u0441\u043E\u043A \u043C\u043E\u0434\u0435\u043B\u0435\u0439");
    refreshBtn.onclick = async () => {
      await this.refreshModels();
    };
    await this.refreshModels();
    containerEl.createEl("hr");
    containerEl.createEl("h2", { text: "\u041A\u043E\u043D\u0442\u0435\u043A\u0441\u0442 \u0438 \u0442\u043E\u043A\u0435\u043D\u044B" });
    new import_obsidian.Setting(containerEl).setName("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u0430\u044F \u0434\u043B\u0438\u043D\u0430 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430").setDesc("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E\u0435 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432 \u0432 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0435 \u0434\u043B\u044F \u0447\u0430\u0442\u0430 (\u0432\u043A\u043B\u044E\u0447\u0430\u044F \u0437\u0430\u043F\u0440\u043E\u0441 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u0438 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u044B)").addText(
      (text) => text.setPlaceholder("4000").setValue(this.plugin.settings.maxContextLength.toString()).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxContextLength = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0418\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u044C Map-Reduce \u0434\u043B\u044F \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432").setDesc("\u0415\u0441\u043B\u0438 \u0432\u043A\u043B\u044E\u0447\u0435\u043D\u043E, \u043A\u0430\u0436\u0434\u044B\u0439 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442 \u0431\u0443\u0434\u0435\u0442 \u0441\u043D\u0430\u0447\u0430\u043B\u0430 \u0441\u0443\u043C\u043C\u0438\u0440\u043E\u0432\u0430\u043D \u043E\u0442\u0434\u0435\u043B\u044C\u043D\u043E, \u0437\u0430\u0442\u0435\u043C \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u043E\u0431\u044A\u0435\u0434\u0438\u043D\u044F\u0442\u0441\u044F \u0432 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442 (\u043B\u0443\u0447\u0448\u0435 \u0434\u043B\u044F \u0431\u043E\u043B\u044C\u0448\u043E\u0433\u043E \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u0430 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useMapReduce).onChange(async (value) => {
        this.plugin.settings.useMapReduce = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E\u0435 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0442\u043E\u043A\u0435\u043D\u043E\u0432").setDesc("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E\u0435 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0442\u043E\u043A\u0435\u043D\u043E\u0432 \u0434\u043B\u044F \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438 \u043E\u0442\u0432\u0435\u0442\u0430").addText(
      (text) => text.setPlaceholder("2048").setValue(this.plugin.settings.maxTokens.toString()).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxTokens = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0422\u0435\u043C\u043F\u0435\u0440\u0430\u0442\u0443\u0440\u0430").setDesc("\u041A\u0440\u0435\u0430\u0442\u0438\u0432\u043D\u043E\u0441\u0442\u044C \u043E\u0442\u0432\u0435\u0442\u0430 (0.0 - \u0434\u0435\u0442\u0435\u0440\u043C\u0438\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439, 1.0 - \u043A\u0440\u0435\u0430\u0442\u0438\u0432\u043D\u044B\u0439)").addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0442\u0435\u0433\u0430\u043C").setDesc("\u0422\u0435\u0433\u0438 \u0434\u043B\u044F \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u0446\u0438\u0438 \u0444\u0430\u0439\u043B\u043E\u0432 \u043F\u0440\u0438 \u0432\u044B\u0431\u043E\u0440\u0435 '\u0412\u0441\u0435 \u0444\u0430\u0439\u043B\u044B' (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043F\u044F\u0442\u0443\u044E). \u0415\u0441\u043B\u0438 \u043F\u0443\u0441\u0442\u043E \u2014 \u0432\u0441\u0435 \u0444\u0430\u0439\u043B\u044B.").addText(
      (text) => {
        var _a2;
        return text.setPlaceholder("important, recent").setValue(((_a2 = this.plugin.settings.includeTags) == null ? void 0 : _a2.join(", ")) || "").onChange(async (value) => {
          const tags = value.split(",").map((t) => t.trim()).filter(Boolean);
          this.plugin.settings.includeTags = tags.length > 0 ? tags : void 0;
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian.Setting(containerEl).setName("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u0432\u043E\u0437\u0440\u0430\u0441\u0442 \u0444\u0430\u0439\u043B\u043E\u0432 (\u0434\u043D\u0438)").setDesc("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u0432\u043E\u0437\u0440\u0430\u0441\u0442 \u0444\u0430\u0439\u043B\u043E\u0432 \u0432 \u0434\u043D\u044F\u0445 (0 \u2014 \u0432\u0441\u0435 \u0444\u0430\u0439\u043B\u044B)").addText(
      (text) => {
        var _a2;
        return text.setPlaceholder("7").setValue(((_a2 = this.plugin.settings.maxFileAge) == null ? void 0 : _a2.toString()) || "0").onChange(async (value) => {
          const days = parseInt(value);
          if (!isNaN(days) && days >= 0) {
            this.plugin.settings.maxFileAge = days;
            await this.plugin.saveSettings();
          }
        });
      }
    );
    new import_obsidian.Setting(containerEl).setName("\u0418\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u044C \u0438\u043D\u0434\u0435\u043A\u0441 \u0444\u0430\u0439\u043B\u043E\u0432").setDesc("\u0412\u043C\u0435\u0441\u0442\u043E \u043F\u043E\u043B\u043D\u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0435\u043D\u0442\u0430 \u0434\u043E\u0431\u0430\u0432\u043B\u044F\u0442\u044C \u0438\u043D\u0434\u0435\u043A\u0441 \u0444\u0430\u0439\u043B\u043E\u0432 (\u0438\u043C\u0435\u043D\u0430, \u0440\u0430\u0437\u043C\u0435\u0440\u044B, \u043A\u043B\u044E\u0447\u0435\u0432\u044B\u0435 \u0441\u043B\u043E\u0432\u0430) \u0434\u043B\u044F \u0440\u0430\u0431\u043E\u0442\u044B \u0441\u043E \u0432\u0441\u0435\u043C\u0438 \u0444\u0430\u0439\u043B\u0430\u043C\u0438 vault").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useFileIndex).onChange(async (value) => {
        this.plugin.settings.useFileIndex = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C \u0444\u0430\u0439\u043B\u043E\u0432 \u0432 \u0438\u043D\u0434\u0435\u043A\u0441\u0435").setDesc("\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E\u0435 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0444\u0430\u0439\u043B\u043E\u0432 \u0434\u043B\u044F \u0432\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u044F \u0432 \u0438\u043D\u0434\u0435\u043A\u0441 (0 - \u0432\u0441\u0435)").addText(
      (text) => {
        var _a2;
        return text.setPlaceholder("50").setValue(((_a2 = this.plugin.settings.maxIndexFiles) == null ? void 0 : _a2.toString()) || "50").onChange(async (value) => {
          const num = parseInt(value);
          if (!isNaN(num) && num >= 0) {
            this.plugin.settings.maxIndexFiles = num;
            await this.plugin.saveSettings();
          }
        });
      }
    );
    containerEl.createEl("hr");
    containerEl.createEl("h2", { text: "\u0420\u0430\u0431\u043E\u0447\u0438\u0435 \u043F\u0430\u043F\u043A\u0438" });
    new import_obsidian.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0438 \u0434\u043B\u044F \u0440\u0430\u0431\u043E\u0442\u044B").setDesc("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043F\u0430\u043F\u043A\u0438, \u043A\u043E\u0442\u043E\u0440\u044B\u0435 \u0431\u0443\u0434\u0443\u0442 \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u044C\u0441\u044F \u0434\u043B\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u0438 \u043F\u043E\u0438\u0441\u043A\u0430. \u0415\u0441\u043B\u0438 \u043D\u0435 \u0432\u044B\u0431\u0440\u0430\u043D\u043E \u2014 \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u044E\u0442\u0441\u044F \u0432\u0441\u0435.").addButton((btn) => {
      btn.setButtonText("\u0412\u044B\u0431\u0440\u0430\u0442\u044C \u043F\u0430\u043F\u043A\u0438");
      btn.onClick(async () => {
        const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((f) => f.path);
        const modal = new FolderSelectModal(this.app, this.plugin.settings.includeFolders || [], folders, async (selected) => {
          this.plugin.settings.includeFolders = selected;
          await this.plugin.saveSettings();
          this.display();
        });
        modal.open();
      });
    }).setDesc("\u0422\u0435\u043A\u0443\u0449\u0438\u0435: " + (((_a = this.plugin.settings.includeFolders) == null ? void 0 : _a.length) ? this.plugin.settings.includeFolders.join(", ") : "\u0432\u0441\u0435 \u043F\u0430\u043F\u043A\u0438"));
    containerEl.createEl("hr");
    class FolderSelectModal extends import_obsidian.Modal {
      constructor(app, selected, allFolders, onChoose) {
        super(app);
        this.selected = [...selected];
        this.allFolders = allFolders;
        this.onChoose = onChoose;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043F\u0430\u043F\u043A\u0438" });
        const list = contentEl.createDiv();
        this.allFolders.forEach((folder) => {
          const item = list.createDiv();
          const checkbox = item.createEl("input", { type: "checkbox" });
          checkbox.checked = this.selected.includes(folder);
          checkbox.onchange = () => {
            if (checkbox.checked) {
              this.selected.push(folder);
            } else {
              this.selected = this.selected.filter((f) => f !== folder);
            }
          };
          item.createSpan({ text: folder });
        });
        const actions = contentEl.createDiv();
        const okBtn = actions.createEl("button", { text: "OK" });
        okBtn.onclick = () => {
          this.onChoose(this.selected);
          this.close();
        };
        const cancelBtn = actions.createEl("button", { text: "\u041E\u0442\u043C\u0435\u043D\u0430" });
        cancelBtn.onclick = () => this.close();
      }
    }
    new import_obsidian.Setting(containerEl).setName("\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u0438\u0435").setDesc("\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u0441\u043E\u0435\u0434\u0438\u043D\u0435\u043D\u0438\u0435 \u0441 LM Studio \u0438 \u043E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0441\u043F\u0438\u0441\u043E\u043A \u043C\u043E\u0434\u0435\u043B\u0435\u0439").addButton(
      (btn) => btn.setButtonText("\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C").onClick(async () => {
        const connected = await this.plugin.checkConnection();
        if (connected) {
          await this.refreshModels();
          new import_obsidian.Notice(`\u2705 \u041F\u043E\u0434\u043A\u043B\u044E\u0447\u0435\u043D\u043E! \u041D\u0430\u0439\u0434\u0435\u043D\u043E \u043C\u043E\u0434\u0435\u043B\u0435\u0439: ${this.plugin.availableModels.length}`);
        } else {
          new import_obsidian.Notice("\u274C \u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0438\u0442\u044C\u0441\u044F \u043A LM Studio");
        }
      })
    );
    containerEl.createEl("h2", { text: "\u041F\u0440\u043E\u043C\u043F\u0442\u044B" });
    new import_obsidian.Setting(containerEl).setName("\u041F\u0440\u043E\u043C\u043F\u0442 \u0434\u043B\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438").setDesc("\u0421\u0438\u0441\u0442\u0435\u043C\u043D\u044B\u0439 \u043F\u0440\u043E\u043C\u043F\u0442 \u0434\u043B\u044F \u0441\u0443\u043C\u043C\u0430\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u043E\u0432").addTextArea((text) => {
      text.setValue(this.plugin.settings.summarizePrompt).onChange(async (value) => {
        this.plugin.settings.summarizePrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      text.inputEl.cols = 50;
    });
    new import_obsidian.Setting(containerEl).setName("\u041F\u0440\u043E\u043C\u043F\u0442 \u0434\u043B\u044F \u0432\u043E\u043F\u0440\u043E\u0441\u043E\u0432").setDesc("\u0421\u0438\u0441\u0442\u0435\u043C\u043D\u044B\u0439 \u043F\u0440\u043E\u043C\u043F\u0442 \u0434\u043B\u044F \u043E\u0442\u0432\u0435\u0442\u043E\u0432 \u043D\u0430 \u0432\u043E\u043F\u0440\u043E\u0441\u044B").addTextArea((text) => {
      text.setValue(this.plugin.settings.questionPrompt).onChange(async (value) => {
        this.plugin.settings.questionPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      text.inputEl.cols = 50;
    });
    containerEl.createEl("h2", { text: "\u0421\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438" });
    new import_obsidian.Setting(containerEl).setName("\u0412\u043A\u043B\u044E\u0447\u0430\u0442\u044C \u0441\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438").setDesc("\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0434\u043E\u0431\u0430\u0432\u043B\u044F\u0442\u044C \u0441\u043E\u0434\u0435\u0440\u0436\u0438\u043C\u043E\u0435 \u0441\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A \u0432 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeLinkedNotes).onChange(async (value) => {
        this.plugin.settings.includeLinkedNotes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0413\u043B\u0443\u0431\u0438\u043D\u0430 \u0441\u0432\u044F\u0437\u0435\u0439").setDesc("\u041D\u0430\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0433\u043B\u0443\u0431\u043E\u043A\u043E \u0438\u0441\u043A\u0430\u0442\u044C \u0441\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 (1-3)").addSlider(
      (slider) => slider.setLimits(1, 3, 1).setValue(this.plugin.settings.maxLinkedNotesDepth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxLinkedNotesDepth = value;
        await this.plugin.saveSettings();
      })
    );
  }
  async refreshModels() {
    if (!this.modelDropdown)
      return;
    this.modelDropdown.empty();
    const loadingOption = this.modelDropdown.createEl("option", {
      text: "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430...",
      value: ""
    });
    const models = await this.plugin.loadAvailableModels();
    this.modelDropdown.empty();
    if (models.length === 0) {
      this.modelDropdown.createEl("option", {
        text: "\u041C\u043E\u0434\u0435\u043B\u0438 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u044B",
        value: ""
      });
      return;
    }
    for (const model of models) {
      const option = this.modelDropdown.createEl("option", {
        text: model.id,
        value: model.id
      });
      if (model.id === this.plugin.settings.model) {
        option.selected = true;
      }
    }
    this.modelDropdown.onchange = async () => {
      this.plugin.settings.model = this.modelDropdown.value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice(`\u0412\u044B\u0431\u0440\u0430\u043D\u0430 \u043C\u043E\u0434\u0435\u043B\u044C: ${this.plugin.settings.model}`);
    };
  }
};
var FolderSelectorModal = class extends import_obsidian.Modal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043F\u0430\u043F\u043A\u0443" });
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((f) => f.path).sort();
    const list = contentEl.createDiv({ cls: "doc-summarize-folder-list" });
    folders.forEach((folder) => {
      const item = list.createDiv({ cls: "doc-summarize-folder-item" });
      (0, import_obsidian.setIcon)(item.createSpan({ cls: "doc-summarize-folder-icon" }), "folder");
      item.createSpan({ text: folder, cls: "doc-summarize-folder-name" });
      item.onclick = () => {
        this.onChoose(folder);
        this.close();
      };
    });
  }
};
